
---
spring:
  config.activate.on-profile: default
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:file::memory:?cache=shared
    hikari:
      max-lifetime: 0
      maximum-pool-size: 1
  config:
    activate:
      on-profile: default
  sql:
    init:
      mode: always
      platform: sqlite
cds:
  security:
    mock:
      enabled: true
      users:
        bob:
          password: bob
          systemUser: true
          roles:
            - SpaceRegistryManager
          additional:
            originPlanet: a11d3f5c-2b91-4c7e-8a3d-9f1c6b2e7a01
