
---
spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:file::memory:?cache=shared
    hikari:
      max-lifetime: 0
      maximum-pool-size: 1
  config:
    activate:
      on-profile: default
  sql:
    init:
      mode: always
      platform: sqlite
